# Generated by Django 3.0.2 on 2020-02-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegreeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='学位名称')),
                ('introduce', models.TextField(verbose_name='类别介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '学位类型信息',
                'verbose_name_plural': '学位类型信息',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='位置名称')),
                ('introduce', models.TextField(verbose_name='位置介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '借调位置信息',
                'verbose_name_plural': '借调位置信息',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='类别名称')),
                ('introduce', models.TextField(verbose_name='类别介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '车辆类别信息',
                'verbose_name_plural': '车辆类别信息',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChengWei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='称谓')),
                ('introduce', models.TextField(verbose_name='说明介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '称谓',
                'verbose_name_plural': '称谓',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DemobilizedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='退伍军人名称')),
                ('introduce', models.TextField(verbose_name='类别介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '退伍军人信息',
                'verbose_name_plural': '退伍军人信息',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiZhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dizhi_id', models.CharField(db_index=True, default='无', max_length=6, unique=True, verbose_name='籍贯编码')),
                ('jiguan', models.CharField(default='无', max_length=50, verbose_name='籍贯')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '籍贯编码',
                'verbose_name_plural': '籍贯编码',
            },
        ),
        migrations.CreateModel(
            name='DrivingLicenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='驾照类别名称')),
                ('introduce', models.TextField(verbose_name='类别介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '驾照类别信息',
                'verbose_name_plural': '驾照类别信息',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Economics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='经济状态名称')),
                ('introduce', models.TextField(verbose_name='经济状态介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '经济状态分类信息',
                'verbose_name_plural': '经济状态分类信息',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='学历名称')),
                ('introduce', models.TextField(verbose_name='类别介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '学历类型信息',
                'verbose_name_plural': '学历类型信息',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='名称')),
                ('introduce', models.TextField(verbose_name='说明介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '婚姻状况',
                'verbose_name_plural': '婚姻状况',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='编制名称')),
                ('introduce', models.TextField(verbose_name='编制介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '编制信息',
                'verbose_name_plural': '编制信息',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PermanentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='名称')),
                ('introduce', models.TextField(verbose_name='说明介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '户籍类别',
                'verbose_name_plural': '户籍类别',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Politics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='名称')),
                ('introduce', models.TextField(verbose_name='说明介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '政治面貌',
                'verbose_name_plural': '政治面貌',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RenYuanXianZhuang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='人员现状')),
                ('introduce', models.TextField(verbose_name='说明介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '人员现状',
                'verbose_name_plural': '人员现状',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShenFenGuiLei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='身份归类')),
                ('introduce', models.TextField(verbose_name='说明介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '身份归类',
                'verbose_name_plural': '身份归类',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='来源名称')),
                ('introduce', models.TextField(verbose_name='来源介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '经济来源分类信息',
                'verbose_name_plural': '经济来源分类信息',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TiJianJieGuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='体检结果')),
                ('introduce', models.TextField(verbose_name='说明介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '体检结果',
                'verbose_name_plural': '体检结果',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='XueLiInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='学历说明名称')),
                ('introduce', models.TextField(verbose_name='学历说明介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '学历说明分类',
                'verbose_name_plural': '学历说明分类',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, default=2019, unique=True, verbose_name='体检年份')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '体检年份',
                'verbose_name_plural': '体检年份',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='YongGongType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='名称')),
                ('introduce', models.TextField(verbose_name='说明介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '人员状态',
                'verbose_name_plural': '人员状态',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ZhuangTai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='名称')),
                ('introduce', models.TextField(verbose_name='说明介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '人员状态',
                'verbose_name_plural': '人员状态',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DaduiZhongduiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='分组名称', max_length=30, verbose_name='分组名称')),
                ('desc', models.TextField(default='', help_text='分组描述', verbose_name='分组描述')),
                ('index', models.IntegerField(default=999, verbose_name='菜单顺序')),
                ('category_type', models.CharField(choices=[('人员', '人员'), ('大队', '大队'), ('中队', '中队'), ('小组', '小组')], help_text='类目级别', max_length=10, verbose_name='类目级别')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='classification.DaduiZhongduiType', verbose_name='父类级别')),
            ],
            options={
                'verbose_name': '大队、中队、小组设置',
                'verbose_name_plural': '大队、中队、小组设置',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='类别名称')),
                ('introduce', models.TextField(verbose_name='类别介绍')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
                ('category_type', models.CharField(choices=[('人员类别', '人员类别'), ('岗位类别', '岗位类别'), ('岗位名称', '岗位名称')], help_text='类目级别', max_length=10, verbose_name='类目级别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='classification.CategoryType', verbose_name='父类级别')),
            ],
            options={
                'verbose_name': '人员类别信息',
                'verbose_name_plural': '人员类别信息',
                'ordering': ['index', 'id'],
            },
        ),
    ]
