# Generated by Django 3.0.2 on 2020-01-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicdegreetype',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='cartype',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='categorytype',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='chengwei',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='daduitype',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='demobilizedtype',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='dizhi',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='drivinglicensetype',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='economics',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='educationtype',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='postname',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='posttype',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='renyuanxianzhuang',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='shenfenguilei',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='sources',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='tijianjieguo',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='xueliinformation',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='zhongduitype',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
