# Generated by Django 3.0.2 on 2020-01-30 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20200119_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaduiZhongduiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='分组名称', max_length=30, verbose_name='分组名称')),
                ('desc', models.TextField(default='', help_text='分组描述', verbose_name='分组描述')),
                ('index', models.IntegerField(default=999, verbose_name='菜单顺序')),
                ('category_type', models.CharField(choices=[('大队', '大队'), ('中队', '中队'), ('小组', '小组')], help_text='类目级别', max_length=10, verbose_name='类目级别')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='classification.DaduiZhongduiType', verbose_name='父类级别')),
            ],
            options={
                'verbose_name': '大队、中队、小组设置',
                'verbose_name_plural': '大队、中队、小组设置',
                'ordering': ['index'],
            },
        ),
    ]
