# Generated by Django 3.0.2 on 2020-01-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_daduizhongduitype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daduizhongduitype',
            name='category_type',
            field=models.CharField(choices=[('人员', '人员'), ('大队', '大队'), ('中队', '中队'), ('小组', '小组')], help_text='类目级别', max_length=10, verbose_name='类目级别'),
        ),
    ]
