# Generated by Django 2.2.7 on 2019-11-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinformation',
            name='birthday',
            field=models.DateField(blank=True, help_text='系统自动生成', null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='politics',
            field=models.CharField(choices=[('群众', '群众'), ('共青团员', '共青团员'), ('中共党员', '中共党员')], default='群众', max_length=10, verbose_name='政治面貌'),
        ),
    ]
