# Generated by Django 3.0.2 on 2020-02-23 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200222_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangtuan',
            name='is_effective',
        ),
    ]
