# Generated by Django 3.0.2 on 2020-01-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200119_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='permanenttype',
            field=models.CharField(choices=[('城镇', '城镇'), ('农村', '农村')], default='', max_length=10, verbose_name='户籍类别'),
        ),
    ]
