# Generated by Django 3.0.2 on 2020-01-21 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200120_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinformation',
            options={'ordering': ['id'], 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
