# Generated by Django 3.0.2 on 2020-01-28 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0004_auto_20200121_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='idnumber',
            field=models.CharField(db_index=True, help_text='身份证号，如果最后一位为X请大写', max_length=18, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='name',
            field=models.CharField(db_index=True, help_text='姓名', max_length=10, verbose_name='姓名'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='角色名称', max_length=25, verbose_name='角色名称')),
                ('range', models.CharField(choices=[('个人', '个人'), ('中队', '中队'), ('大队', '大队'), ('所有', '所有')], default='个人', help_text='角色控制数据的范围', max_length=10, verbose_name='控制范围')),
                ('group', models.OneToOneField(help_text='与角色对应的用户组，控制角色权限', on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='用户组')),
                ('users', models.ManyToManyField(help_text='用户角色，控制用户访问与数据修改权限', related_name='users_role', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
