# Generated by Django 3.0.2 on 2020-01-28 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0005_auto_20200128_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.OneToOneField(blank=True, help_text='与角色对应的用户组，控制角色权限', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='用户组'),
        ),
    ]
