# Generated by Django 3.0.2 on 2020-02-08 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200208_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangtuan',
            name='name',
            field=models.ForeignKey(help_text='姓名', on_delete=django.db.models.deletion.CASCADE, related_query_name='dangtuan', to='users.PersonalInformation', verbose_name='姓名'),
        ),
    ]
