# Generated by Django 3.0.2 on 2020-01-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200128_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='range',
            new_name='ranges',
        ),
    ]
