# Generated by Django 3.0.2 on 2020-01-29 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20200119_2145'),
        ('users', '0009_auto_20200129_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='drivinglicense',
            field=models.ForeignKey(blank=True, default=1, help_text='驾照', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.DrivingLicenseType', verbose_name='驾照'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='economics',
            field=models.ForeignKey(blank=True, help_text='家庭经济状态', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.Economics', verbose_name='家庭经济状态'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='hobby',
            field=models.CharField(default='无', help_text='爱好/特长', max_length=100, verbose_name='爱好/特长'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='marriage',
            field=models.CharField(choices=[('已婚', '已婚'), ('未婚', '未婚'), ('离婚', '离婚'), ('丧偶', '丧偶')], default='未婚', help_text='婚姻状态', max_length=10, verbose_name='婚姻状态'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='mobile',
            field=models.CharField(help_text='手机号码', max_length=11, unique=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='named',
            field=models.CharField(default='无', help_text='曾用名', max_length=10, verbose_name='曾用名'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='nation',
            field=models.CharField(choices=[('汉族', '汉族'), ('壮族', '壮族'), ('满族', '满族'), ('回族', '回族'), ('苗族', '苗族'), ('维吾尔族', '维吾尔族'), ('土家族', '土家族'), ('彝族', '彝族'), ('蒙古族', '蒙古族'), ('藏族', '藏族'), ('布依族', '布依族'), ('侗族', '侗族'), ('瑶族', '瑶族'), ('朝鲜族', '朝鲜族'), ('白族', '白族'), ('哈尼族', '哈尼族'), ('哈萨克族', '哈萨克族'), ('黎族', '黎族'), ('傣族', '傣族'), ('畲族', '畲族'), ('傈僳族', '傈僳族'), ('仡佬族', '仡佬族'), ('东乡族', '东乡族'), ('高山族', '高山族'), ('拉祜族', '拉祜族'), ('水族', '水族'), ('佤族', '佤族'), ('纳西族', '纳西族'), ('羌族', '羌族'), ('土族', '土族'), ('仫佬族', '仫佬族'), ('锡伯族', '锡伯族'), ('柯尔克孜族', '柯尔克孜族'), ('达斡尔族', '达斡尔族'), ('景颇族', '景颇族'), ('毛南族', '毛南族'), ('撒拉族', '撒拉族'), ('布朗族', '布朗族'), ('塔吉克族', '塔吉克族'), ('阿昌族', '阿昌族'), ('普米族', '普米族'), ('鄂温克族', '鄂温克族'), ('怒族', '怒族'), ('京族', '京族'), ('基诺族', '基诺族'), ('德昂族', '德昂族'), ('保安族', '保安族'), ('俄罗斯族', '俄罗斯族'), ('裕固族', '裕固族'), ('乌孜别克族', '乌孜别克族'), ('门巴族', '门巴族'), ('鄂伦春族', '鄂伦春族'), ('独龙族', '独龙族'), ('塔塔尔族', '塔塔尔族'), ('赫哲族', '赫哲族'), ('珞巴族', '珞巴族')], default='汉族', help_text='民族', max_length=10, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='permanenttype',
            field=models.CharField(choices=[('城镇', '城镇'), ('农村', '农村')], default='', help_text='户籍类别', max_length=10, verbose_name='户籍类别'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='politics',
            field=models.CharField(choices=[('群众', '群众'), ('共青团员', '共青团员'), ('中共党员', '中共党员')], default='群众', help_text='政治面貌', max_length=10, verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='politicstime',
            field=models.DateField(blank=True, help_text='入党/团时间', null=True, verbose_name='入党/团时间'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', help_text='性别，默认为“男”,系统会根据身份证自动判断', max_length=5, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='sources',
            field=models.ForeignKey(blank=True, help_text='家庭经济状态，经济来源', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.Sources', verbose_name='家庭经济状态，经济来源'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='veteran',
            field=models.ForeignKey(blank=True, help_text='退役类别', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.DemobilizedType', verbose_name='退役类别'),
        ),
    ]
