# Generated by Django 3.0.2 on 2020-01-29 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20200119_2145'),
        ('users', '0010_auto_20200129_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='role',
            name='ranges_dadui',
            field=models.ManyToManyField(help_text='可以访问的数据范围：大队', to='classification.DaDuiType', verbose_name='权限大队'),
        ),
        migrations.AddField(
            model_name='role',
            name='ranges_zhongdui',
            field=models.ManyToManyField(help_text='可以访问的数据范围：中队（小组）', to='classification.ZhongDuiType', verbose_name='权限中队（小组）'),
        ),
        migrations.AddField(
            model_name='role',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
