# Generated by Django 3.0.2 on 2020-02-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200208_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='idfj',
            field=models.CharField(default='未分配', help_text='辅警编号', max_length=10, verbose_name='辅警编号'),
        ),
    ]
