# Generated by Django 3.0.2 on 2020-02-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200208_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yonggong',
            name='name',
            field=models.ForeignKey(help_text='姓名', on_delete=django.db.models.deletion.CASCADE, related_name='yonggongs', to='users.PersonalInformation', verbose_name='姓名'),
        ),
    ]
