# Generated by Django 3.0.2 on 2020-01-29 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200129_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(help_text='用户角色，控制用户访问与数据修改权限', related_name='users_role', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
