# Generated by Django 3.0.2 on 2020-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20200119_2145'),
        ('users', '0012_auto_20200129_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='ranges_dadui',
            field=models.ManyToManyField(blank=True, help_text='可以访问的数据范围：大队', to='classification.DaDuiType', verbose_name='权限大队'),
        ),
        migrations.AlterField(
            model_name='role',
            name='ranges_zhongdui',
            field=models.ManyToManyField(blank=True, help_text='可以访问的数据范围：中队（小组）', to='classification.ZhongDuiType', verbose_name='权限中队（小组）'),
        ),
    ]
