# Generated by Django 3.0.2 on 2020-02-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200211_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinformation',
            options={'ordering': ['dadui', 'fenzu'], 'verbose_name': '个人档案', 'verbose_name_plural': '个人档案'},
        ),
    ]
