# Generated by Django 3.0.2 on 2020-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20200119_2145'),
        ('users', '0014_auto_20200129_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='ranges',
        ),
        migrations.AlterField(
            model_name='role',
            name='ranges_zhongdui',
            field=models.ManyToManyField(blank=True, help_text='可以访问的数据范围：中队（小组），要选择此项必须选择大队选项', to='classification.ZhongDuiType', verbose_name='权限中队（小组）'),
        ),
    ]
