# Generated by Django 3.0.2 on 2020-01-30 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_daduizhongduitype'),
        ('users', '0015_auto_20200129_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='fenzu',
            field=models.ForeignKey(blank=True, help_text='所属分组，本信息由管理员填写', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.DaduiZhongduiType', verbose_name='所属分组'),
        ),
    ]
