# Generated by Django 3.0.2 on 2020-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200131_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='idnumber',
            field=models.CharField(db_index=True, help_text='身份证号，如果最后一位为X请大写', max_length=18, unique=True, verbose_name='身份证'),
        ),
    ]
