# Generated by Django 3.0.2 on 2020-01-31 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200131_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='idnumber',
            field=models.CharField(db_index=True, help_text='身份证号，如果最后一位为X请大写，字段在数据库中必须唯一', max_length=18, unique=True, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='mobile',
            field=models.CharField(help_text='手机号码，字段在数据库中必须唯一"', max_length=11, unique=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='user',
            field=models.OneToOneField(help_text='关联的账号，一对一关联，必须唯一', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
