# Generated by Django 2.2.7 on 2020-01-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='菜单名称', max_length=30, verbose_name='菜单名称')),
                ('desc', models.TextField(default='', help_text='菜单描述', verbose_name='菜单描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级菜单'), (2, '二级菜单'), (3, '三级菜单')], help_text='类目级别', verbose_name='类目级别')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父菜单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='vue_pms.Menu', verbose_name='父类菜单级别')),
            ],
            options={
                'verbose_name': '菜单设置',
                'verbose_name_plural': '菜单设置',
            },
        ),
    ]
