# Generated by Django 3.0.2 on 2020-02-29 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vue_pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteconfig',
            options={'ordering': ['-add_time'], 'verbose_name': '前端网站设置', 'verbose_name_plural': '前端网站设置'},
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='is_look',
            field=models.BooleanField(default=False, help_text='是否有效', verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
