# Generated by Django 2.2.7 on 2020-01-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_pms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='class_img',
            field=models.CharField(default='', help_text='Element图标', max_length=100, verbose_name='class图标'),
        ),
    ]
