# Generated by Django 2.2.7 on 2020-01-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_pms', '0002_menu_class_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['index'], 'verbose_name': '菜单设置', 'verbose_name_plural': '菜单设置'},
        ),
        migrations.AddField(
            model_name='menu',
            name='index',
            field=models.IntegerField(default=999, verbose_name='菜单顺序'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_look',
            field=models.BooleanField(default=False, help_text='是否显示到菜单中', verbose_name='是否显示'),
        ),
    ]
