# Generated by Django 2.2.7 on 2020-01-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_pms', '0003_auto_20200107_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='设置网站的名称', max_length=30, verbose_name='网站名称')),
                ('logo', models.ImageField(default='WebsiteConfig/logo.png', max_length=250, upload_to='WebsiteConfig/%Y/%m/%d/', verbose_name='网站LOGO')),
            ],
        ),
    ]
