# Generated by Django 2.2.7 on 2020-01-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue_pms', '0004_websiteconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteconfig',
            options={'verbose_name': '前端网站设置', 'verbose_name_plural': '前端网站设置'},
        ),
    ]
